# This script creates a list of recent blog posts and passes them to the template context.

def on_config(config):
    # Ensure the required blog plugin is enabled
    if 'blog' not in config['plugins']:
        print("Warning: The 'blog' plugin is required for recent posts hook to work.")
    return config

def on_page_context(context, page, config, nav):
    # Only run this logic for the Home page (index.md)
    if page.file.src_uri == 'index.md':
        
        # Access the blog posts generated by the mkdocs-blog plugin
        # This assumes the blog plugin has already run and populated the nav
        blog_nav_item = next((item for item in nav.items if item.title == 'Blogs'), None)
        
        # Find the actual posts list, often nested under the 'index' file of the blog
        if blog_nav_item and hasattr(blog_nav_item, 'children'):
            # The 'children' here are usually the blog index, archive, etc.
            # We want the posts themselves, which are collected by the blog plugin internally.
            
            # Since accessing the internal post list directly is tricky, we'll iterate 
            # through the *pages* that are part of the 'blog' collection.
            
            # A more stable way is to look for the blog pages in the global files object
            # (Note: This is an approximation since direct post access is not standard via the nav object)
            
            posts = []
            
            # We'll use a simple filter: check all pages for the 'blog/posts' path
            for f in config['files']:
                if f.src_uri.startswith('blog/posts/') and f.page.is_page:
                    posts.append({
                        'title': f.page.title,
                        'url': f.page.url,
                        'date': f.page.meta.get('date', 'Unknown Date') # Get date from front matter
                    })
            
            # Sort by date descending and limit to 5
            posts.sort(key=lambda p: p['date'], reverse=True)
            
            context['recent_posts'] = posts[:5]
            
    return context
